<html>
	<head>
        <link rel="stylesheet" type="text/css" href="css/navigation.css">
        <title>Academic Enrichment</title>
	</head>
	<body>
		<div id="navigation">
            <h1>Academic Enrichment</h1>

            <a class="navigation-button" href="Add/addDetention.phtml">Add Detention</a>
            <a class="navigation-button" href="Add/addStudent.phtml">Add Student</a>
            <a class="navigation-button" href="#.phtml">View Detentions</a>
            <a class="navigation-button" href="View/Form/viewStudentsForm.phtml">View Student</a>
		</div>
		
	</body>
</html>