<html>
	<head>
        <link rel="stylesheet" type="text/css" href="css/navigation.css">
        <title>Academic Enrichment</title>
	</head>
	<body>
		<div id="navigation">
            <h1>Academic Enrichment</h1>
            <a class="navigation-button" href="Manage/manageAttendance.phtml">Attendance</a>
            <a class="navigation-button" href="Manage/manageStudent.phtml">Students</a>
            <a class="navigation-button" href="Manage/manageDetention.phtml">Detentions</a>
            <a class="navigation-button" href="Manage/manageStaff.phtml">Staff</a>
            <a class="navigation-button" href="Manage/manageSubject.phtml">Subjects</a>
            <a class="navigation-button" href="Manage/manageReport.phtml">Reports</a>
            <a class="navigation-button" href="Manage/manageAccount.phtml">Accounts</a>
		</div>

	</body>
</html>