<html>
<head>
    <link rel="stylesheet" type="text/css" href="../../css/common.css">
    <title>View Student</title>
</head>
<h1>View Staff</h1>

<p>Please select a role</p>

<form action="../viewStaff.php" method="POST">
    <label>Role: </label>
    <select name="role">
        <option value="TeacherFlag">Teacher</option>
        <option value="AdminFlag">Admin</option>
        <option value="CeaFlag">CEA</option>
        <option value="all" selected >All</option>
    </select>

    <input type="submit" value="Submit">
</form>


</html>