<html>
<head>
    <link rel="stylesheet" type="text/css" href="../../css/common.css">
    <title>View Academic Enrichment Referrals</title>
</head>
<h1>View Academic Enrichment Referrals</h1>


<form action="../viewDetentions.php" method="POST">
    <select name="detention-select">
        <option value="complete">Completed</option>
        <option value="incomplete">Not Completed</option>
        <option value="all" selected >All</option>
    </select>

    <input type="submit" value="Submit">
</form>


</html>