<html>
    <head>
        <link rel="stylesheet" type="text/css" href="../../css/common.css">
        <title>View Student</title>
    </head>
    <h1>View Student</h1>

    <p>Please select a grade</p>

    <form action="../Submit/viewStudents.php" method="POST">
        <select name="grade">
            <option value="8">8th Gr</option>
            <option value="9">9th Gr</option>
            <option value="10">10th Gr</option>
            <option value="11">11th Gr</option>
            <option value="12">12th Gr</option>
            <option value="all">All</option>
        </select>

        <input type="submit">
    </form>


</html>