<html>
<body>
<head>
    <link rel="stylesheet" type="text/css" href="../css/add-student.css">
    <title>Add Account</title>
</head>
<div id="addAccount">
    <h1>Add Account</h1>

    //auto fill all fields from database, search with text entered

    <form action ="../Submit/submitAccount.php" method="POST">
        <div class="form-piece">
            <label>Name:</label>
            <input type="text" name="name">
        </div>



        <input type="submit" value="Submit">
    </form>

</div>
</body>
</html>