<html>
    <body>
    <head>
        <link rel="stylesheet" type="text/css" href="../css/add-student.css">
        <title>Add Student</title>
    </head>
    <div id="addStudent">
    <h1>Add Student</h1>
        <form action ="../Submit/submitStudent.php" method="POST">
            <div class="form-piece">
                <div class="form-label"><label>First Name:</label></div>
                <input type="text" name="first_name">
            </div>

            <div class="form-piece">
                <div class="form-label"><label>Last Name:</label></div>
                <input type="text" name="last_name">
            </div>

            <div class="form-piece">
                <div class="form-label"><label>Grade:</label></div>
                <input type="text" name="grade">
            </div>

            <div class="form-piece">
                <div class="form-label"><label>Student Email:</label></div>
                <input type="text" name="student_email">
            </div>

            <div class="form-piece">
                <div class="form-label"><label>Parent Email:</label></div>
                <input type="text" name="parent_email">
            </div>

            <div class="form-piece">
                <div class="form-label"><label>Second Parent Email:</label></div>
                <input type="text" name="parent_email2">
            </div>

                <input type="submit" value="Submit">
        </form>
        </div>
    </body>
</html>