<html>
<head>
    <link rel="stylesheet" type="text/css" href="../css/navigation.css">
    <title>Manage Staff</title>
</head>
<body>
<div id="navigation">
    <div class="breadcrumbs">
        <a href="../index.phtml">Home</a>
    </div>
    <h1>Manage Staff</h1>
    <a class="navigation-button" href="../Add/addStaff.phtml">Add New Staff Member</a>

    <iframe src="../View/viewStaff.php" width="800" height="400"></iframe>

</div>

</body>
</html>