<html>
<head>
    <link rel="stylesheet" type="text/css" href="../css/navigation.css">
    <title>Manage Account</title>
</head>
<body>
<div id="navigation">
    <h1>Manage Account</h1>
    <a class="navigation-button" href="Add/addAccount.phtml">Add New Account</a>
    <a class="navigation-button" href="Edit/editAccount.phtml">Edit Account</a>
    <a class="navigation-button" href="Delete/deleteAccount.phtml">Delete Account</a>
</div>

</body>
</html>