<html>
<head>
    <link rel="stylesheet" type="text/css" href="../css/navigation.css">
    <title>Manage Subjects</title>
</head>
<body>
<div id="navigation">
    <a href="../index.phtml">Home</a>
    <h1>Manage Subjects</h1>
    <a class="navigation-button" href="../Add/addSubject.phtml">Add New Subject</a>

    <iframe src="../View/viewSubjects.php" width="800" height="400"></iframe>
</div>

</body>
</html>