<html>
<head>
    <link rel="stylesheet" type="text/css" href="../css/navigation.css">
    <title>Manage Attendance</title>
</head>
<body>
<div id="navigation">
    <a href="../index.phtml">Home</a>
    <h1>Manage Attendance</h1>
    <a class="navigation-button" href="Add/addAttendance.phtml">Add New Attendance</a>
    <a class="navigation-button" href="Edit/editAttendance.phtml">Edit Attendance</a>
    <a class="navigation-button" href="Delete/deleteAttendance.phtml">Delete Attendance</a>
</div>

</body>
</html>