<html>
<body>
<head>
    <link rel="stylesheet" type="text/css" href="../css/add-student.css">
    <title>Subjects</title>
</head>
<div id="subject">
    <h1>Subjects</h1>
    <!-- <form action ="../Submit/submitTeacher.php" method="POST"> -->

    <div class="form-piece">
        <label>put in subject stuff:</label>
        <input type="text" name="username">
    </div>

    <div class="form-piece">
        <label>Password:</label>
        <input type="text" name="password">
    </div>

    <input type="submit" value="Login"> <br>
    <input type="submit" value="Forgot Password">
    </form>
</div>
</body>
</html>