<html>
<head>
    <link rel="stylesheet" type="text/css" href="../css/navigation.css">
    <title>Manage Academic Enrichment Referrals</title>
</head>
<body>
<div id="navigation">
    <a href="../index.phtml">Home</a>
    <h1>Manage Academic Enrichment Referrals</h1>
    <a class="navigation-button" href="../Add/addDetention.php">Add New Referral</a>

    <iframe src="../View/Form/viewDetentionsForm.phtml" width="800" height="400"></iframe>
</div>

</body>
</html>