<html>
<head>
    <link rel="stylesheet" type="text/css" href="../css/navigation.css">
    <title>Manage Teacher</title>
</head>
<body>
<div id="navigation">
    <h1>Manage Teacher</h1>
    <a class="navigation-button" href="../Add/addTeacher.phtml">Add New Teacher</a>
    <a class="navigation-button" href="../Edit/editTeacher.phtml">Edit Teacher</a>
    <a class="navigation-button" href="../Delete/deleteTeacher.phtml">Delete Teacher</a>
</div>

</body>
</html>