<html>
<head>
    <link rel="stylesheet" type="text/css" href="../css/navigation.css">
    <title>Manage Detention</title>
</head>
<body>
<div id="navigation">
    <a href="../index.phtml">Home</a>
    <h1>Manage Detention</h1>
    <a class="navigation-button" href="../Add/addDetention.php">Add New Detention</a>
    <a class="navigation-button" href="Edit/editDetention.phtml">Edit Detention</a>
    <a class="navigation-button" href="Delete/deleteDetention.phtml">Delete Detention</a>
</div>

</body>
</html>