<html>
<head>
    <link rel="stylesheet" type="text/css" href="../css/navigation.css">
    <title>Manage Student</title>
</head>
<body>
<div id="navigation">
    <div class="breadcrumbs">
        <a href="../index.phtml">Home</a>
    </div>
    <h1>Manage Student</h1>
    <a class="navigation-button" href="../Add/addStudent.phtml">Add New Student</a>

    <iframe src="../View/Form/viewStudentsForm.phtml" width="800" height="400"></iframe>
</div>

</body>
</html>