<html>
<head>
    <link rel="stylesheet" type="text/css" href="../css/navigation.css">
    <title>Manage Report</title>
</head>
<body>
<div id="navigation">
    <h1>Manage Reports</h1>
    <a class="navigation-button" href="Reports/AttendanceReport.phtml">Attendance Report</a>
    <a class="navigation-button" href="Reports/StudentReport.phtml">Student Report</a>
    <a class="navigation-button" href="Reports/DetentionReport.phtml">Detention Report</a>
    <a class="navigation-button" href="Reports/TeacherReport.phtml">Teacher Report</a>
    <a class="navigation-button" href="Reports/AccountReport.phtml">Account Report</a>
</div>

</body>
</html>